name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use latest version (v3) of actions/checkout
        with:
          ref: ${{ github.ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send email
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python pages/Contact.py